name: Build and Deploy
on:
  push:	
    branches:	
      - master
  pull_request:
    branches:
      - master
  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Build and Deploy
      uses: y4code/hexo-deploy-action@master
      env:
        PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_REPOSITORY: hykhd/hykhd # The repository the action should deploy to.
        BRANCH: gh-pages  # The branch the action should deploy to.
        PUBLISH_DIR: ./public # The folder the action should deploy.